(function(){
'use strict';
var CACHE={rows:[],loaded:false};
function esc(v){return String(v==null?'':v).replace(/[&<>\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]})}
function first(o,ks){for(var i=0;i<ks.length;i++){var v=o&&o[ks[i]];if(v!==undefined&&v!==null&&v!=='')return v}return null}
function obj(o,k){return o&&o[k]&&typeof o[k]==='object'?o[k]:{}}
function rows(){if(window.FILTERED&&Array.isArray(window.FILTERED))return window.FILTERED;if(window.DATA&&Array.isArray(window.DATA.opportunities))return window.DATA.opportunities;return CACHE.rows}
function load(){return fetch('/data/latest-opportunities.json?t='+Date.now(),{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}).then(function(x){CACHE.rows=x&&Array.isArray(x.opportunities)?x.opportunities:[];CACHE.loaded=true;return CACHE.rows}).catch(function(){CACHE.loaded=true;return CACHE.rows})}
function country(o){return String(first(o,['buyer-country','buyer_country','project_ctry_name','country_name'])||'Bilinmiyor')}
function region(o){return String(first(o,['market_region','regionname'])||'Diğer')}
function w(o){return obj(o,'workflow')}
function status(o,k){return String((w(o)[k]&&w(o)[k].status)||'')}
function buyerOk(o){return o.buyer_verified===true||status(o,'buyer').indexOf('verified')>=0}
function supplierOk(o){var sr=obj(o,'supplier_research');return o.supplier_status==='verified'||Number(sr.verified_count||0)>0||Number(obj(w(o),'supplier').verified_candidates||0)>0}
function pricingOk(o){var pm=obj(w(o),'pricing_margin'),p=obj(o,'price_agent');return pm.supplier_quote!=null||pm.sell_price!=null||(p.status&&p.status!=='quote_pending')}
function logisticsOk(o){var lw=obj(w(o),'logistics'),l=obj(o,'logistics_agent');return lw.freight!=null||lw.landed_cost!=null||(l.status&&l.status!=='route_pending')}
function riskOk(o){var s=(obj(o,'risk_agent').status||status(o,'risk'));return !!s&&s!=='due_diligence_pending'}
function contractOk(o){var s=status(o,'contract');return ['signed','active','approved','completed'].indexOf(s)>=0}
function commissionOk(o){var p=obj(w(o),'commission_protection'),pm=obj(w(o),'pricing_margin');return !!(p.status&&p.status!=='not_started')||pm.commission!=null}
function offerOk(o){return o.offer_status==='active'||['approved','ready','sent','active'].indexOf(status(o,'offer'))>=0}
function count(a,fn){var n=0;for(var i=0;i<a.length;i++)if(fn(a[i]))n++;return n}
function metric(label,value,note){return '<div class="gbmetric"><b>'+esc(value)+'</b><span>'+esc(label)+'</span>'+(note?'<small>'+esc(note)+'</small>':'')+'</div>'}
function topCountries(a){var m={};a.forEach(function(o){var c=country(o);m[c]=(m[c]||0)+1});return Object.keys(m).sort(function(x,y){return m[y]-m[x]}).slice(0,6).map(function(c){return '<div class="gbrow"><span>'+esc(c)+'</span><b>'+m[c]+'</b></div>'}).join('')||'<div class="gbempty">Henüz ülke verisi yok.</div>'}
function topRegions(a){var m={};a.forEach(function(o){var r=region(o);m[r]=(m[r]||0)+1});return Object.keys(m).sort(function(x,y){return m[y]-m[x]}).slice(0,6).map(function(r){return '<div class="gbrow"><span>'+esc(r)+'</span><b>'+m[r]+'</b></div>'}).join('')||'<div class="gbempty">Henüz pazar verisi yok.</div>'}
function agentHtml(a){var n=a.length;return '<div class="gblive"><h3>Canlı Ajan Operasyon Durumu</h3><p>Rakamlar mevcut fırsat havuzundan hesaplanır; veri yoksa başarı varsayılmaz.</p><div class="gbmetrics">'+metric('Opportunity Agent',n,'fırsat havuzu')+metric('Buyer Agent',count(a,buyerOk),'doğrulanmış alıcı')+metric('Supplier Agent',count(a,supplierOk),'eşleşen tedarikçi')+metric('Price Agent',count(a,pricingOk),'fiyat verisi ilerlemiş')+metric('Logistics Agent',count(a,logisticsOk),'rota/navlun ilerlemiş')+metric('Risk Agent',count(a,riskOk),'inceleme ilerlemiş')+metric('Contract Agent',count(a,contractOk),'aktif/imzalı')+metric('Commission Agent',count(a,commissionOk),'takibe girmiş')+'</div><div class="gbnote">Shadow Mode: dış mesaj, sözleşme veya para hareketi insan onayı olmadan yapılmaz.</div></div>'}
function reportHtml(a){var n=a.length,b=count(a,buyerOk),s=count(a,supplierOk),p=count(a,pricingOk),l=count(a,logisticsOk),r=count(a,riskOk),o=count(a,offerOk);return '<div class="gblive"><h3>Yönetici Günlük Operasyon Özeti</h3><div class="gbmetrics">'+metric('Toplam fırsat',n)+metric('Alıcı doğrulandı',b)+metric('Tedarikçi eşleşti',s)+metric('Fiyat ilerledi',p)+metric('Lojistik ilerledi',l)+metric('Risk ilerledi',r)+metric('Teklif aşaması',o)+metric('Ticari blokaj',Math.max(0,n-Math.min(b,s,p,l,r)),'en az bir kritik alan eksik')+'</div><div class="gbcols"><div><h4>En yoğun ülkeler</h4>'+topCountries(a)+'</div><div><h4>Pazar dağılımı</h4>'+topRegions(a)+'</div></div></div>'}
function settingsHtml(a){return '<div class="gblive"><h3>Sistem Durumu</h3><div class="gbmetrics">'+metric('Veri havuzu',a.length,'yüklenen fırsat')+metric('Shadow Mode','AÇIK','insan onayı zorunlu')+metric('Dış işlem','KİLİTLİ','otomatik gönderim yok')+metric('Veri politikası','KANITLI','kaynakta olmayan veri üretilmez')+'</div><div class="gbnote"><b>Operasyon politikası:</b> Kaynak doğrulaması, alıcı/tedarikçi kontrolü, gerçek fiyat, lojistik ve risk kapıları tamamlanmadan bağlayıcı ticari işlem ilerletilmez.</div></div>'}
function style(){if(document.getElementById('gbOperationalStyle'))return;var s=document.createElement('style');s.id='gbOperationalStyle';s.textContent='.gblive{margin:14px 0 22px;padding:16px;border:1px solid #31536a;border-radius:16px;background:#091f2f}.gblive h3{margin:0 0 6px}.gblive>p{margin:0 0 13px;color:#aebfca}.gbmetrics{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.gbmetric{background:#0d2a3e;border:1px solid #284b62;border-radius:12px;padding:11px;min-width:0}.gbmetric b{display:block;font-size:20px;color:#f3a14d}.gbmetric span{display:block;font-size:11px;font-weight:800;margin-top:2px}.gbmetric small{display:block;color:#8fa5b5;font-size:9px;margin-top:3px}.gbcols{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:14px}.gbcols>div{background:#071a27;border-radius:12px;padding:12px}.gbcols h4{margin:0 0 8px}.gbrow{display:flex;justify-content:space-between;gap:10px;padding:6px 0;border-bottom:1px solid #17384d;font-size:12px}.gbrow:last-child{border:0}.gbnote{margin-top:12px;padding:11px;border-left:3px solid #f3923c;background:#0a2234;border-radius:8px;color:#c7d4dc;font-size:12px}.gbempty{color:#8fa5b5;font-size:12px}@media(max-width:560px){.gbcols{grid-template-columns:1fr}.gbmetrics{grid-template-columns:repeat(2,minmax(0,1fr))}}';document.head.appendChild(s)}
function append(kind){style();var host=document.getElementById('pc')||document.getElementById('content');if(!host)return;var old=host.querySelector('.gblive');if(old)old.remove();var a=rows(),box=document.createElement('div');if(kind==='agents')box.innerHTML=agentHtml(a);else if(kind==='report')box.innerHTML=reportHtml(a);else if(kind==='settings')box.innerHTML=settingsHtml(a);else return;host.insertBefore(box.firstChild,host.firstChild)}
function wrapCustomer(){if(typeof window.openCard!=='function'||window.openCard.__gbLive)return;var old=window.openCard;window.openCard=function(k,t){old(k,t);if(k==='agents'||k==='report'||k==='settings'){load().then(function(){append(k)})}};window.openCard.__gbLive=true}
function wrapApp(){if(typeof window.openTab!=='function'||window.openTab.__gbLive)return;var old=window.openTab;window.openTab=function(k){old(k);if(k==='agents'||k==='report'||k==='settings'){load().then(function(){append(k)})}};window.openTab.__gbLive=true}
style();load();wrapCustomer();wrapApp();
})();