(function(){
'use strict';
var ROWS=[];
function esc(v){return String(v==null?'':v).replace(/[&<>\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]})}
function s(v){return String(v==null?'':v).trim()}
function norm(v){return s(v).toLocaleLowerCase('tr-TR').replace(/\s+/g,' ')}
function pick(o,ks,fallback){for(var i=0;i<ks.length;i++){var v=o&&o[ks[i]];if(v!==undefined&&v!==null&&v!=='')return v}return fallback===undefined?'Bekleniyor':fallback}
function obj(o,k){return o&&o[k]&&typeof o[k]==='object'?o[k]:{}}
function title(o){return pick(o,['title_tr','title_original','notice-title'],'Başlık bekleniyor')}
function country(o){return pick(o,['buyer-country','buyer_country','project_ctry_name','country_name'],'Ülke bekleniyor')}
function city(o){return pick(o,['buyer-city','buyer_city','city','project_city','town','locality','place'],'Şehir bekleniyor')}
function buyer(o){return pick(o,['buyer-name','buyer_name','buyer','project_name'],'Alıcı bekleniyor')}
function summary(o){return pick(o,['demand_summary_tr','detail_tr','description-lot','description','title_tr'],'Talep özeti bekleniyor')}
function product(o){return pick(o,['product','product_name','product_category','cpv_description','classification-cpv','categories'],'Ürün ayrıştırması bekleniyor')}
function quantity(o){return pick(o,['quantity-lot','quantity','estimated_quantity','volume'],'Miktar bekleniyor')}
function budget(o){return pick(o,['estimated-value-lot','estimated_value','budget','amount','value'],'Bütçe bekleniyor')}
function deadline(o){return pick(o,['deadline-receipt-tender-date-lot','submission_deadline_date','deadline'],'Son tarih bekleniyor')}
function delivery(o){return pick(o,['delivery_location','delivery-place','delivery_place','place-of-performance','place_of_performance'],'Teslim yeri bekleniyor')}
function links(o){var ks=['url','source_url','notice_url','official_url','document_url','documents_url','tender_url'],out=[];ks.forEach(function(k){var v=s(o&&o[k]);if(/^https?:\/\//i.test(v)&&out.indexOf(v)<0)out.push(v)});return out}
function meaningful(v){var x=norm(v);return !!x&&!/(pending|not_started|bekleniyor|unknown|research_pending|route_pending|due_diligence_pending)/.test(x)}
function statusClass(v){var x=norm(v);if(/signed|active|approved|verified|completed|ready/.test(x))return 'good';if(/pending|research|review|bekleniyor|not_started/.test(x))return 'warn';return 'neutral'}
function field(label,value){return '<div class="gbd-field"><small>'+esc(label)+'</small><b>'+esc(value)+'</b></div>'}
function pill(label,value){return '<span class="gbd-pill '+statusClass(value)+'">'+esc(label)+': '+esc(value)+'</span>'}
function section(titleText,body){return '<section class="gbd-section"><h4>'+esc(titleText)+'</h4>'+body+'</section>'}
function readiness(o){var w=obj(o,'workflow'),sr=obj(o,'supplier_research'),pm=obj(w,'pricing_margin'),lg=obj(w,'logistics'),la=obj(o,'logistics_agent'),rk=obj(w,'risk'),ra=obj(o,'risk_agent');var buyerOk=o.buyer_verified===true;var supplierOk=o.supplier_status==='verified'||Number(sr.verified_count||0)>0;var quote=pm.supplier_quote!==undefined&&pm.supplier_quote!==null&&pm.supplier_quote!=='';var logistics=meaningful(lg.status)||meaningful(la.status)||((lg.freight||la.freight)&&(lg.incoterm||la.incoterm));var risk=meaningful(rk.status)||meaningful(ra.status);if(buyerOk&&supplierOk&&quote&&logistics&&risk)return ['Hazır inceleme','good'];if(buyerOk&&supplierOk&&quote)return ['Ticari veri güçlü','strong'];if(buyerOk||supplierOk)return ['Araştırma sürüyor','warn'];return ['Eksik dosya','bad']}
function sourceLinks(o){var a=links(o);if(!a.length)return '<div class="gbd-muted">Doğrulanmış kaynak bağlantısı bekleniyor.</div>';return '<div class="gbd-links">'+a.slice(0,3).map(function(x,i){return '<a href="'+esc(x)+'" target="_blank" rel="noopener">'+(i===0?'Resmî kaynak':'Belge / Kaynak '+(i+1))+'</a>'}).join('')+'</div>'}
function render(o,host,titleHost,back){var w=obj(o,'workflow'),sr=obj(o,'supplier_research'),pm=obj(w,'pricing_margin'),lg=obj(w,'logistics'),la=obj(o,'logistics_agent'),rk=obj(w,'risk'),ra=obj(o,'risk_agent'),ct=obj(w,'contract'),cp=obj(w,'commission_protection'),pay=obj(w,'payment'),rd=readiness(o);var riskStatus=ra.status||rk.status||'Risk incelemesi bekleniyor';var logisticStatus=la.status||lg.status||'Lojistik incelemesi bekleniyor';var contractStatus=ct.status||'not_started';var supplierStatus=sr.status||o.supplier_status||'research_pending';var quote=pm.supplier_quote==null?'Gerçek teklif bekleniyor':pm.supplier_quote;var commission=pm.commission==null?pick(o,['commission_potential','commission_status'],'Hesaplanmadı'):pm.commission;var html='<button class="gbd-back" type="button">← Fırsatlar listesine dön</button><article class="gbd-dossier"><div class="gbd-head"><div><div class="gbd-kicker">GLOBAL BROKER · FIRSAT DOSYASI</div><h3>'+esc(title(o))+'</h3><div class="gbd-location">'+esc(country(o))+' · '+esc(city(o))+'</div></div><span class="gbd-state '+rd[1]+'">'+rd[0]+'</span></div>';
html+=section('1 · Talep', '<p class="gbd-summary">'+esc(summary(o))+'</p><div class="gbd-grid">'+field('Ürün / Kalem',product(o))+field('Miktar',quantity(o))+field('Bütçe / Değer',budget(o))+field('Son tarih',deadline(o))+field('Teslim yeri',delivery(o))+field('Fırsat türü',pick(o,['opportunity_type','notice_type','procedure-type'],'Bekleniyor'))+'</div>');
html+=section('2 · Alıcı & Kaynak','<div class="gbd-grid">'+field('Alıcı / Kurum',buyer(o))+field('Alıcı doğrulama',o.buyer_verified===true?'Doğrulandı':'Doğrulama bekleniyor')+field('Kaynak',pick(o,['source'],'Kaynak adı bekleniyor'))+field('Pazar bölgesi',pick(o,['market_region'],'Bölge bekleniyor'))+'</div>'+sourceLinks(o));
html+=section('3 · Tedarik','<div class="gbd-grid">'+field('Aranan ürün',sr.product_query||product(o))+field('Doğrulanmış aday',String(sr.verified_count||0))+field('Tedarikçi durumu',supplierStatus)+field('Türkiye tedarik durumu',pick(o,['turkey_supply_status'],'Bekleniyor'))+'</div><div class="gbd-pills">'+pill('Supplier Agent',supplierStatus)+'</div>');
html+=section('4 · Fiyat & Lojistik','<div class="gbd-grid">'+field('Tedarikçi teklifi',quote)+field('Satış fiyatı',pm.sell_price==null?'Hesaplanmadı':pm.sell_price)+field('Brüt marj',pm.gross_margin==null?'Hesaplanmadı':pm.gross_margin)+field('Incoterm',lg.incoterm||la.incoterm||'Bekleniyor')+field('Navlun',lg.freight||la.freight||'Bekleniyor')+field('Landed cost',lg.landed_cost||'Hesaplanmadı')+'</div><div class="gbd-pills">'+pill('Logistics',logisticStatus)+'</div>');
html+=section('5 · Risk & Uyum','<div class="gbd-grid">'+field('Risk incelemesi',riskStatus)+field('Ödeme riski',rk.payment_risk||'Bekleniyor')+field('Ülke riski',rk.country_risk||'Bekleniyor')+field('Broker değerlendirmesi',pick(o,['broker_opportunity'],'Bekleniyor'))+'</div><div class="gbd-pills">'+pill('Risk Agent',riskStatus)+'</div>');
html+=section('6 · Sözleşme & Komisyon','<div class="gbd-grid">'+field('Sözleşme',contractStatus)+field('Komisyon',commission)+field('Komisyon koruması',cp.status||'not_started')+field('Koruma süresi',cp.target_months?(cp.target_months+' ay'):'Sözleşmeye göre')+field('Ödeme durumu',pay.status||'not_started')+field('Bağlayıcı işlem','İnsan onayı zorunlu')+'</div><div class="gbd-pills">'+pill('Contract',contractStatus)+pill('Commission',cp.status||'not_started')+'</div>');
html+='<div class="gbd-foot">Bu ekran mevcut kaynak ve iş akışı verilerini düzenler; eksik fiyat, alıcı, tedarikçi veya ticari şart üretmez.</div></article>';
host.innerHTML=html;if(titleHost)titleHost.textContent='Fırsat Dosyası';var b=host.querySelector('.gbd-back');if(b)b.onclick=back;window.scrollTo(0,0)}
function bestMatch(text,meta){var nt=norm(text),nm=norm(meta),best=null,score=-1;ROWS.forEach(function(o){var t=norm(title(o)),sc=0;if(t===nt)sc+=10;else if(nt&&t&&((nt.indexOf(t)>=0)||(t.indexOf(nt)>=0)))sc+=5;var hay=norm([country(o),pick(o,['source'],'')].join(' '));if(nm&&hay&&nm.split(' ').some(function(x){return x.length>3&&hay.indexOf(x)>=0}))sc+=2;if(sc>score){score=sc;best=o}});return score>=5?best:null}
function openCustomer(btn){var host=document.getElementById('pc');if(!host)return false;var t=btn.querySelector('b'),m=btn.querySelector('small'),o=bestMatch(t?t.textContent:'',m?m.textContent:'');if(!o)return false;render(o,host,document.getElementById('pt'),function(){if(typeof window.openCard==='function')window.openCard('opps','Fırsatlar')});return true}
function enhanceCards(){var host=document.getElementById('content')||document.getElementById('pc');if(!host)return;[].slice.call(host.querySelectorAll('.opp')).forEach(function(card){if(card.classList.contains('gbd-dossier')||card.dataset.gbd==='1')return;var h=card.querySelector('h3');if(!h)return;var o=bestMatch(h.textContent,card.textContent);if(!o)return;card.dataset.gbd='1';var b=document.createElement('button');b.type='button';b.className='gbd-open';b.textContent='Dosyayı aç →';b.onclick=function(e){e.preventDefault();e.stopPropagation();var target=document.getElementById('content')||document.getElementById('pc');var th=document.getElementById('title')||document.getElementById('pt');render(o,target,th,function(){if(typeof window.openTab==='function')window.openTab('opps');else if(typeof window.openCard==='function')window.openCard('opps','Fırsatlar')})};card.appendChild(b)})}
function style(){if(document.getElementById('gbd-style'))return;var st=document.createElement('style');st.id='gbd-style';st.textContent='.gbd-dossier{background:#081e2d;border:1px solid #31536a;border-radius:18px;padding:16px;margin:12px 0 24px}.gbd-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start;padding-bottom:14px;border-bottom:1px solid #24465d}.gbd-head h3{margin:4px 0 6px;font-size:21px;line-height:1.3}.gbd-kicker{font-size:10px;letter-spacing:.12em;color:#f3a14d;font-weight:900}.gbd-location{font-size:11px;color:#9fb1bd}.gbd-state{font-size:10px;font-weight:900;padding:7px 9px;border-radius:999px;border:1px solid #31536a;white-space:nowrap}.gbd-state.good{color:#8ee0bd;border-color:#35755d;background:#0c2c27}.gbd-state.strong{color:#9ec8ff;border-color:#39658b;background:#0a2940}.gbd-state.warn{color:#efd08a;border-color:#7f6230;background:#2a2416}.gbd-state.bad{color:#f0a5ae;border-color:#743e46;background:#2a171b}.gbd-section{padding:15px 0;border-bottom:1px solid #17384d}.gbd-section:last-of-type{border-bottom:0}.gbd-section h4{margin:0 0 11px;color:#f3a14d;font-size:13px;letter-spacing:.03em}.gbd-summary{font-size:15px;line-height:1.6;margin:0 0 12px}.gbd-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.gbd-field{background:#0d2a3e;border:1px solid #27485d;border-radius:11px;padding:10px;min-width:0}.gbd-field small{display:block;color:#8fa5b5;font-size:9px;margin-bottom:4px;text-transform:uppercase;letter-spacing:.05em}.gbd-field b{display:block;font-size:12px;line-height:1.4;overflow-wrap:anywhere}.gbd-pills{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.gbd-pill{font-size:9px;border:1px solid #31536a;border-radius:999px;padding:5px 7px;color:#c7d4dc}.gbd-pill.good{color:#8ee0bd;border-color:#35755d}.gbd-pill.warn{color:#efd08a;border-color:#7f6230}.gbd-links{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.gbd-links a{background:#173b52;border:1px solid #31536a;color:#fff;text-decoration:none;padding:8px 10px;border-radius:9px;font-size:11px}.gbd-muted{color:#8fa5b5;font-size:11px;margin-top:8px}.gbd-foot{margin-top:14px;padding:10px;border-left:3px solid #f3923c;background:#0a2234;border-radius:8px;color:#b8c7d1;font-size:10px;line-height:1.5}.gbd-back,.gbd-open{border:0;border-radius:10px;padding:10px 12px;background:#f3a14d;color:#071827;font-weight:900;cursor:pointer}.gbd-open{margin-top:10px;font-size:11px}@media(max-width:560px){.gbd-grid{grid-template-columns:1fr}.gbd-head{flex-direction:column}.gbd-state{align-self:flex-start}.gbd-dossier{padding:13px}}';document.head.appendChild(st)}
function start(){style();document.addEventListener('click',function(e){var btn=e.target.closest&&e.target.closest('.noticebtn');if(!btn)return;if(openCustomer(btn)){e.preventDefault();e.stopImmediatePropagation()}},true);new MutationObserver(function(){enhanceCards()}).observe(document.body,{childList:true,subtree:true});enhanceCards()}
function load(){if(Array.isArray(window.__GB_OPPORTUNITY_ROWS)&&window.__GB_OPPORTUNITY_ROWS.length){ROWS=window.__GB_OPPORTUNITY_ROWS;start();return}fetch('/data/latest-opportunities.json?t='+Date.now(),{cache:'no-store'}).then(function(r){return r.json()}).then(function(x){ROWS=x&&Array.isArray(x.opportunities)?x.opportunities:[];window.__GB_OPPORTUNITY_ROWS=ROWS;start()}).catch(function(){start()})}
load();
})();